
INSERT INTO `origine` (`nom`, `description`, `place_moyenne`) VALUES
('Darkin', 'Lorsqu\'Aatrox ou le détenteur de la lame Darkin meurt, la lame Darkin est équipée au champion allié le plus proche, lui accordant 400 points de vie et 15 % d\'Omnivamp.', 3),
('Démacia', 'Vos Demaciens les plus forts deviennent Élite et équipent un objet Radiant aléatoire à chaque combat. Les élites accordent de l\'armure et de la résistance magique à elles-mêmes et à leurs alliés adjacents, mais cela ne se cumule pas.', 4),
('Impératrice', 'Lorsque Bel\'Veth tue un ennemi, celui-ci laisse derrière lui du Corail du Vide qu\'elle consommera. Le premier corail augmente sa santé maximale de 50 %, tandis que le corail suivant soigne sa santé maximale de 20 %.', 3),
('Freljord', 'Après 8 secondes, une tempête de verglas frappe le champ de bataille. Les ennemis subissent un pourcentage de leur santé maximale sous forme de dégâts réels et bénéficient de débuffs.\r\nSunder : réduire l\'armure\r\nShred : réduire la résistance magique\r\nMana Reave : augmenter le mana maximum jusqu\'au prochain lancement.', 2),
('Ionia', 'Chaque Ionien possède un bonus unique au sein de sa capacité.\r\nToutes les 4 secondes, un certain nombre d\'Ioniens sont éclairés à leur forme spirituelle, gagnant 20 mana et doublant les bonus de statistiques pendant 4 secondes.', 4),
('Noxus', 'Les champions de Noxus gagnent de la santé, de la puissance et des dégâts d\'attaque.\r\nCeci est augmenté de 5% pour chaque adversaire différent que vous avez vaincu au combat ou qui est mort.', 6),
('Piltover', 'Gagnez le T-Hex.\r\nChaque fois que vous perdez un combat, le T-Hex gagne des Charges.\r\nGagner convertit les charges en puissance pour le T-Hex.\r\n\r\nVous pouvez également vendre le T-Hex s\'il a du pouvoir, en réinitialisant le T-Hex et en convertissant son pouvoir en butin.', 5),
('Îles obscures', 'Après avoir infligé ou reçu des dégâts 10 fois, les champions des Îles obscures gagnent un bouclier pendant 15 secondes et deviennent Spectral pour le reste du combat.\r\nLes unités spectrales gagnent du mana chaque seconde.', 3),
('Shurima', 'Toutes les 4 secondes, le Shuriman soigne 5 % de sa santé maximale.\r\nAprès 8 secondes, sélectionnez le Shuriman Ascend et gagnez 33 % de santé maximale et 45 % de vitesse d\'attaque.', 6),
('Targon', 'Tous les soins et boucliers de votre unité sont améliorés.', 2),
('Néant', 'Obtenez un œuf vide plaçable.\r\nAu début du combat, il se transforme en une horreur indescriptible et projette les ennemis adjacents.\r\nChaque niveau d\'étoile du Néant augmente la santé et la puissance de l\'horreur de 25 %.', 3),
('Vagabond', 'Le sort de Ryze change en fonction du portail de région pour lequel les joueurs ont voté au début de la partie.', 5),
('Yordle', 'Vos unités gagnent 10 % de vitesse d\'attaque par niveau d\'étoile.\r\nSi vous avez des champions 3 étoiles, vos Yordles peuvent devenir 4 étoiles, ce qui donne à leur capacité une amélioration farfelue !', 5),
('Zaun', 'Les champions Zaun créent des mods chimiques aléatoires qu\'eux seuls peuvent utiliser.\r\nLes champions peuvent être modifiés une fois, et les mods ne peuvent être supprimés qu\'en vendant le champion.', 5),
('Bastion', 'Les champions du Bastion gagnent en armure et en résistance magique.\r\nCelui-ci est augmenté de 100% pendant les 10 premières secondes de combat.', 6),
('Combattant', 'Vos unités gagnent 100 points de vie.\r\nLes Combattants gagnent un maximum de santé supplémentaire.', 7),
('Challenger', 'Les challengers bénéficient d\'un bonus de vitesse d\'attaque.\r\nLorsque leur cible meurt, les Challengers se précipitent vers une nouvelle cible et augmentent leur bonus de vitesse d\'attaque de 50 % pendant 2,5 secondes.', 1),
('Tireur d\'élite', 'Inné : +1 portée\r\nToutes les 3 secondes, les Tireurs d\'élite attaquent l\'ennemi avec le pourcentage de santé le plus élevé et inflige des dégâts supplémentaires.', 1),
('Canonnier', 'Lorsque les champions Canonnier attaquent, ils gagnent des dégâts d\'attaque supplémentaires, jusqu\'à 8 charges.', 5),
('Incantateur', 'Toutes les 3 secondes, vos unités gagnent du Mana.', 4),
('Colosse', 'Les champions Colosse subissent moins de dégâts', 7),
('Multimage', 'Les multimages lancent leur capacité plusieurs fois. Les lancers bonus ont une efficacité réduite de 66 %.', 5),
('Rédemptrice', 'Chaque fois qu\'un allié gagne un bouclier, accordez-lui une vitesse d\'attaque cumulable de 6 % pour le reste du combat.', 2),
('Bourreau', 'Les champions Bourreau gagnent 12% d\'Omnivamp.\r\nIls infligent des dégâts supplémentaires, doublés contre les unités ayant moins de 66 % de santé.', 4),
('Rebelle', 'Les Rebelles se déplacent rapidement.', 6),
('Sorcier', 'Les Sorciers gagnent un bonus de puissance.\r\nLorsqu\'un ennemi meurt après avoir été blessé par un Sorcier, il inflige un pourcentage de la santé maximale de cet ennemi à un autre ennemi.', 5),
('Stratège', 'Début du combat : les alliés des 2 premières rangées gagnent un bouclier pendant 15 secondes.\r\nLes alliés des 2 dernières rangées gagnent en puissance.', 4),
('Génie', 'Obtenez une tourelle Apex plaçable avec 3 emplacements de mise à niveau.\r\nLes améliorations de la tourelle Apex apparaîtront dans votre boutique pour 6 pièces d\'or.\r\nLa tourelle Apex partage la vitesse d\'attaque et la puissance de Heimerdinger.', 5);

